VERSION = 0.1

PREFIX = /usr/local
MANPREFIX = $(PREFIX)/share/man

CFLAGS = -Wall -pedantic -std=c99
CPPFLAGS = -DVERSION=\"$(VERSION)\" -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600
STCFLAGS = $(CPPFLAGS) $(CFLAGS)
